server:
  port: 8080
  servlet:
    contextPath: /companieshouse

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health

spring:
  application:
    name: companies-house-microservice
  resources:
    add-mappings: true
  profiles:
    active: default

logging:
  level:
    org:
      springframework:
        web: ERROR
        cloud:
          kubernetes: DEBUG
    com:
      uk:
        companieshouse: DEBUG

govCompaniesHouse:
  endpoint: https://api.companieshouse.gov.uk/search/companies?q={companyRef}
  authUserName: dummy-auth-user
