version: 2.1

executors:
  base-jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
  circleci-ubuntu:
    docker:
      - image: cimg/base:2020.01
  trivy:
    docker:
      - image: aquasec/trivy:latest
  helm:
    docker:
      - image: nukengprodservice/helm:latest
  owasp-zap:
    docker:
      - image: owasp/zap2docker-stable:latest

aliases:
  - &mount_workspace
    attach_workspace:
      at: .
  - &restore_gradlew_cache
    restore_cache:
      keys:
        - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &restore_gradle_cache
    restore_cache:
      keys:
        - v1-gradle-cache-{{ checksum "build.gradle" }}
  - &save_dependency_vulnerability_cache
    save_cache:
      key: v1-dependency-cache-{{ checksum "build.gradle" }}
      paths:
        - /home/circleci/.gradle/dependency-check-data/4.0/
  - &restore_dependency_vulnerability_cache
    restore_cache:
      keys:
        - v1-dependency-cache-{{ checksum "build.gradle" }}
  - &only_master
    filters:
      branches:
        only: master
  - &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - .
  - &credential_context
    context: credentials

jobs:
  build:
    executor: base-jdk8
    description: Install dependencies & Build
    steps:
      - checkout
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: Install Dependencies
          command: |
            ./gradlew build -x test -x checkstyleTest
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - *persist_to_workspace

  test:
    executor: base-jdk8
    description: Unit Test & Code Coverage
    steps:
      - *mount_workspace
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: Run Unit and E2E tests
          command: ./gradlew test
      - store_artifacts:
          path: build/reports/tests/test
          when: always
      - store_test_results:
          path: build/test-results/test
          when: always
      - *persist_to_workspace

  gradle_execute_task:
    executor: base-jdk8
    parameters:
      step_name:
        type: string
        default: executing the task
      gradle_task:
        type: string
      artifact_path:
        type: string
    steps:
      - *mount_workspace
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: << parameters.step_name >>
          command: ./gradlew '<< parameters.gradle_task >>'
      - store_artifacts:
          path: << parameters.artifact_path >>
          when: always

  check_dependency_vulnerability:
    executor: base-jdk8
    parameters:
      timeout:
        description: Execution timeout for running the step command
        type: string
        default: 10m
    description: Dependency Vulnerability Check
    steps:
      - *mount_workspace
      - checkout
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - *restore_dependency_vulnerability_cache
      - run:
          name: Perform Dependency Vulnerability Checks
          no_output_timeout: << parameters.timeout >>
          command: ./gradlew dependencyCheckAnalyze
      - *save_dependency_vulnerability_cache
      - store_test_results:
          path: build/reports/dependency-vulnerabilities
          when: always
      - store_artifacts:
          path: build/reports/dependency-vulnerabilities
          when: always

  build_and_push_image:
    description: Build Docker Image & Push
    executor: base-jdk8
    steps:
      - *mount_workspace
      - setup_remote_docker
      - run:
          name: Docker Image build and push
          command: .circleci/scripts/docker-build.sh
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - version.txt

  check_image_vulnerability:
    description: Use Trivy to check the final docker image vulnerabilities before deployment
    executor: trivy
    steps:
      - checkout
      - run:
          name: Trivy Image Vulnerability Check
          command: |
            apk add --no-cache bash
            /root/project/.circleci/scripts/vulnerability-checks.sh
      - store_artifacts:
          path: reports
          when: always

  helm_deploy:
    executor: helm
    parameters:
      release:
        type: string
    steps:
      - *mount_workspace
      - checkout
      - run:
          name: aws eks config update
          command: aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${EKS_CLUSTER_NAME}
      - run:
          name: helm release
          command: |
            RELEASE_NAME="<< parameters.release >>" \
            EKS_NAMESPACE="${EKS_NAMESPACE}" \
            ./.circleci/scripts/helm-deploy.sh

  health_check:
    executor: circleci-ubuntu
    steps:
      - checkout
      - run:
          name: Perform API Health Check
          command: ./.circleci/scripts/health-check.sh

  penetration_test:
    executor: owasp-zap
    steps:
      - run:
          name: Perform Penetration Test
          command: |
            cd ../../../zap/
            echo "Running from containers home zap directory..."
            mkdir wrk && zap-baseline.py -t "${HEALTH_ENDPOINT}" -g gen.conf -r penetration-test-report.html || :
            echo "Moving Pen Test report to the circleci job working dir.."
            mv wrk/* ../home/zap/project/
      - store_artifacts:
          path: .

workflows:
  version: 2.1
  workflow-all-jobs:
    jobs:
      - build:
          <<: *only_master
          name: Build
      - test:
          name: Unit & E2E Tests
          requires:
            - Build
      - gradle_execute_task:
          name: Jacoco Code Coverage
          step_name: Check Jacoco code coverage & generate report
          gradle_task: jacocoTestCoverageVerification
          artifact_path: build/reports/jacocoHtml
          requires:
            - Unit & E2E Tests
      - gradle_execute_task:
          name: Checkstyle
          step_name: Check styling and generate report
          gradle_task: check
          artifact_path: build/reports/checkstyle
          requires:
            - Build
      - gradle_execute_task:
          name: Mutation Tests
          step_name: Perform Mutation Testing on Unit Tests
          gradle_task: pitest
          artifact_path: build/reports/pitest
          requires:
            - Build
      - check_dependency_vulnerability:
          name: Dependency Vulnerability Checks
          timeout: 20m
          requires:
            - Build
      - build_and_push_image:
          <<: *credential_context
          name: Docker Image build and push
          requires:
            - Jacoco Code Coverage
            - Checkstyle
            - Mutation Tests
            - Dependency Vulnerability Checks
      - check_image_vulnerability:
          <<: *credential_context
          name: Image Vulnerability Check
          requires:
            - Docker Image build and push
      - hold:
          type: approval
          requires:
            - Image Vulnerability Check
      - helm_deploy:
          <<: *credential_context
          name: Deploy app to K8S
          release: companieshouse-release
          requires:
            - Image Vulnerability Check
            - hold
      - health_check:
          <<: *credential_context
          name: Health Check
          requires:
            - Deploy app to K8S
      - penetration_test:
          <<: *credential_context
          name: Penetration Test
          requires:
            - Deploy app to K8S
  scheduled-vulnerability-check:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          <<: *only_master
    jobs:
      - check_dependency_vulnerability:
          name: Dependency Vulnerability Checks
          timeout: 20m
      - check_image_vulnerability:
          name: Image Vulnerability Check
          <<: *credential_context
