version: 2.1

executors:
  base:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
  ubuntu:
    docker:
      - image: ubuntu:latest
  trivy:
    docker:
      - image: aquasec/trivy:latest

aliases:
  - &mount_workspace
    attach_workspace:
      at: .
  - &restore_cache
    restore_cache:
      key: >-
        v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
        v1-gradle-cache-{{ checksum "build.gradle" }}
jobs:
  build:
    executor: base
    description: Install dependencies & Build
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install Dependencies
          command: ./gradlew build -x test -x checkstyleTest
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: base
    description: Unit Test & Code Coverage
    steps:
      - *mount_workspace
      - *restore_cache
      - run:
          name: Run tests in parallel
          # Use "./gradlew test" instead if tests are not run in parallel
          command: |
            cd src/test/java
            # Get list of classnames of tests that should run on this node
            CLASSNAMES=$(circleci tests glob "**/*.java" \
              | cut -c 1- | sed 's@/@.@g' \
              | sed 's/.\{5\}$//' \
              | circleci tests split --split-by=timings --timings-type=classname)
            cd ../../..
            # Format the arguments to "./gradlew test"
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew test $GRADLE_ARGS
      - run:
          name: Generate code coverage report
          command:
            ./gradlew jacocoTestReport
      - run:
          name: Code coverage verification
          command:
            ./gradlew jacocoTestCoverageVerification
      - store_artifacts:
          path: build/reports/jacocoHtml
          when: always
      - store_test_results:
          path: build/reports/tests/test
          when: always
      - run:
          name: Assemble JAR
          command: |
            # Skip this for other nodes
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
              ./gradlew assemble
            fi
      # This will be empty for all nodes except the first one
      - persist_to_workspace:
          root: build
          paths:
            - libs

  checkstyle:
    executor: base
    description: Code Checkstyle check
    steps:
      - *mount_workspace
      - *restore_cache
      - run:
          name: Generate checkstyle coverage report
          command: ./gradlew check
      - store_artifacts:
          path: build/reports/checkstyle
          when: always

  mutationtest:
    executor: base
    description: Mutation Testing
    # Remove if parallelism is not desired
    parallelism: 2
    steps:
      - *mount_workspace
      - *restore_cache
      - run:
          name: Perform Mutation Testing on Unit Test
          command: ./gradlew pitest
      - store_artifacts:
          path: build/reports/pitest
          when: always

  buildAndPushImage:
    description: Build Docker Image & Push
    executor: base
    steps:
      - *mount_workspace
      - setup_remote_docker
      - run:
          name: Docker Image build and push
          command: .circleci/scripts/docker-build.sh

  checkImageVulnerability:
    description: Use Trivy to check the final docker image vulnerabilities before deployment
    executor: trivy
    steps:
      - checkout
      - run:
          name: Image Vulnerability Check
          command: |
            apk add --no-cache bash
            .circleci/scripts/vulnerability-checks.sh
      - store_artifacts:
          path: reports
          when: always

workflows:
  version: 2.1
  workflow-alljobs:
    jobs:
      - build
      - test:
          requires:
            - build
      - checkstyle:
          requires:
            - build
      - mutationtest:
          requires:
            - build
      - buildAndPushImage:
          context: credentials
          requires:
            - test
            - checkstyle
            - mutationtest
      - checkImageVulnerability:
          context: credentials
          requires:
            - buildAndPushImage
