resources:
  - name: source-repo
    type: git
    icon: github
    source:
      branch: master
      uri: https://github.com/abhisheksr01/spring-boot-microservice-best-practices.git
  - name: gradle-jdk8-image
    type: registry-image
    source:
      repository: gradle
      tag: 6.7.1-jdk8

jobs:
  - name: unit-e2e-tests-and-code-coverage
    plan:
      - get: source-repo
        trigger: true
      - get: gradle-jdk8-image
      - task: unit-and-e2e-tests
        file: source-repo/concourse-ci/tasks/gradle/task.yml
        image: gradle-jdk8-image
        params:
          GRADLE_TASK: test
      - task: jacoco-code-coverage
        file: source-repo/concourse-ci/tasks/gradle/task.yml
        image: gradle-jdk8-image
        params:
          GRADLE_TASK: jacocoTestCoverageVerification
  - name: mutation-testing
    plan:
    - get: source-repo
      trigger: true
    - get: gradle-jdk8-image
    - task: pitest
      file: source-repo/concourse-ci/tasks/gradle/task.yml
      image: gradle-jdk8-image
      params:
        GRADLE_TASK: pitest
  - name: static-code-analysis
    plan:
    - get: source-repo
      trigger: true
    - get: gradle-jdk8-image
    - task: checkstyle
      file: source-repo/concourse-ci/tasks/gradle/task.yml
      image: gradle-jdk8-image
      params:
        GRADLE_TASK: check
  - name: dependency-vulnerability-scan
    plan:
    - get: source-repo
      trigger: true
    - get: gradle-jdk8-image
    - task: dependency-check-analyze
      file: source-repo/concourse-ci/tasks/gradle/task.yml
      image: gradle-jdk8-image
      params:
        GRADLE_TASK: dependencyCheckAnalyze