resources:
  - name: source-repo
    type: git
    icon: github
    source:
      branch: master
      uri: https://github.com/abhisheksr01/spring-boot-microservice-best-practices.git
  - name: gradle-jdk8-image
    type: registry-image
    source:
      repository: gradle
      tag: 6.7.1-jdk8

jobs:
  - name: build
    serial: true
    serial_groups: [serial-group]
    plan:
    - get: source-repo
    - get: gradle-jdk8-image
    - task: Mutaion Testing
      file: source-repo/concourse-ci/tasks/gradle/task.yml
      image: gradle-jdk8-image
      params:
        GRADLE_TASK: pitest
    - task: Static Checkstyle
        file: source-repo/concourse-ci/tasks/gradle/task.yml
        image: gradle-jdk8-image
        params:
          GRADLE_TASK: check