name: CICD Pipeline
on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-build-${{ env.cache-name }}-${{ checksum "build.gradle" }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: ( ./gradlew build -x test )
        name: "Executing build"

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-build-${{ env.cache-name }}-${{ checksum "build.gradle" }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: ( ./gradlew test )
        name: "Executing tests"
      - run: ( ./gradlew jacocoTestCoverageVerification )
        name: "Code coverage"
  mutation-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-build-${{ env.cache-name }}-${{ checksum "build.gradle" }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: ( ./gradlew pitest )
        name: "Executing mutation tests"
  dependency-vulnerability-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-build-${{ env.cache-name }}-${{ checksum "build.gradle" }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: ( ./gradlew dependencyCheckAnalyze -PUseNVDKey )
        name: "Executing dependency vulnerability checks"
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}