name: CICD Pipeline
on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - run: ( ./gradlew build -x test )
        name: "Executing build stage"
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - run: ( ./gradlew test )
        name: "Executing tests"
      - run: ( ./gradlew jacocoTestCoverageVerification )
        name: "Code coverage"
  mutation-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - run: ( ./gradlew pitest )
        name: "Executing mutation tests"
  dependency-vulnerability-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - run: ( ./gradlew dependencyCheckAnalyze )
        name: "Executing dependency vulnerability checks"