name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - run: ( ./gradlew clean build )
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
        name: "Executing unit tests and checking code coverage"
      - run: ( ./gradlew pitest )
        name: "Executing mutation tests"
      - run: ( ./gradlew dependencyCheckAnalyze )
        name: "Executing dependency vulnerability checks"